package com.oaup.ocr.common;

/**
 * Created by jkx on 2015/7/17.
 */
public enum Event {
    /** system init **/
    SYSTEM_INIT,
    /** system destory **/
    SYSTEM_DESTORY,

     REQ_FORM_SHOW_MAIN,

     REQ_FORM_SHOW_LOGIN,

    REQ_FORM_SHOW_GUIDE,

    REQ_FORM_SHOW_LIST,

    REQ_HTTP_LOGIN_RESULT,

    REQ_FORM_SHOW_MY_DOCUMENT,

    REQ_FORM_SHOW_DOCUMENT_SUB,

    REQ_FORM_SHOW_DOCUMENT_IMG_EDIT,

    REQ_FORM_SHOW_MY_SHARE,

    REQ_FORM_BACK,

    REQ_FORM_SHOW_TAKE_PIC,

    REQ_BITMAP_CREATED,

    REQ_FORM_SHOW_PIC_CROP,

    REQ_FORM_SHOW_PIC_ENHANCE,

    REQ_FORM_SHOW_FROM_PIC_ENHANCE_TO_MY_DOCUMENT,

    REQ_FORM_SHOW_FROM_PIC_ENHANCE_TO_DOCUMENT_SUB,

    REQ_FORM_SHOW_FROM_PIC_ENHANCE_TO_IMG_EDIT,

    REQ_RESUME_CAMERA,

    REQ_FORM_TAGS,

    REQ_FORM_SHOW_MARK_PROCESS,
}
